#!/bin/sh
B_MNT="/bin/mount -t"
B_UMNT="/bin/umount"
G_BOOTDELAY="0"
G_BOOT_DEV_PART=""
G_TARGET=""

global_setup() {
$B_MNT proc proc /proc
cmd_env=`/bin/cat /proc/cmdline`
export $cmd_env
$B_MNT devtmpfs devtmpfs /dev
$B_MNT sysfs sysfs /sys

G_BOOT_DEV_PART=$BOOT_DEV$BOOT_DEV_PART
G_TARGET="/mnt"
G_BOOT_ON_RAM="$BOOT_ON_RAM"

sleep $BOOT_DELAY
if [ "$G_BOOT_ON_RAM" == "" ];
then
  $B_MNT vfat $G_BOOT_DEV_PART $G_TARGET
else
  $B_MNT tmpfs tmpfs $G_TARGET
  $B_MNT vfat $G_BOOT_DEV_PART /newroot
  cp /newroot/rootfs.squashfs $G_TARGET
  cp /newroot/kmod.squashfs $G_TARGET
  cp /newroot/defaults.squashfs $G_TARGET
  $B_UMNT /newroot
fi
}

global_action() {
if [ -f $G_TARGET/rootfs.squashfs ];
then
  $B_MNT squashfs $G_TARGET/rootfs.squashfs /newroot
fi
if [ -f $G_TARGET/kmod.squashfs ];
then
  $B_MNT squashfs $G_TARGET/kmod.squashfs /newroot/lib/modules
fi
if [ -f $G_TARGET/defaults.squashfs ];
then
  $B_MNT squashfs $G_TARGET/defaults.squashfs /newroot/etc/defaults
fi

if [ -f $G_TARGET/rootfs.squashfs ];
then
  $B_UMNT /proc
  $B_UMNT /sys
  exec switch_root /newroot /init
else
  exec /bin/sh
fi
}

global_setup
global_action
