#!/bin/sh
boot_delay=""
boot_dev=""
boot_rootfs=""
B_MNT="/bin/mount"
B_UMNT="/bin/umount"

mountfs() {
$B_MNT -t proc proc /proc
cmd_env=`/bin/cat /proc/cmdline`
export $cmd_env
$B_MNT -t devtmpfs devtmpfs /dev
$B_MNT -t sysfs sysfs /sys

if [ "$BOOT_DELAY" == "" ];
then
  boot_delay=0
else
  boot_delay=$BOOT_DELAY
fi

if [ "$BOOT_DEV" == "" ];
then
  boot_dev="/dev/sda1"
else
  boot_dev=$BOOT_DEV
fi

if [ "$BOOT_ROOTFS" == "" ];
then
  boot_rootfs="rootfs.squashfs"
else
  boot_rootfs=$BOOT_ROOTFS
fi

echo "Booting from $boot_dev..."
echo "Sleeping $boot_delay seconds..."
echo "Boot rootfs $boot_rootfs"
$B_MNT -t vfat $boot_dev /mnt
}

rootfs_exist() {
$B_UMNT /proc
$B_UMNT /sys
$B_MNT -t squashfs /mnt/$boot_rootfs /newroot
exec switch_root /newroot /init
}

rootfs_not_exist() {
exec /bin/sh
}

mountfs
[ -f /mnt/$boot_rootfs ] && rootfs_exist || rootfs_not_exist
