#!/bin/sh
B_MNT="/bin/mount"
B_UMNT="/bin/umount"

mount_fs_and_export_env() {
$B_MNT -t proc proc /proc
cmd_env=`/bin/cat /proc/cmdline`
export $cmd_env
$B_MNT -t devtmpfs devtmpfs /dev
$B_MNT -t sysfs sysfs /sys
}

mountfs() {
mount_fs_and_export_env

if [ "$BOOT_DELAY" == "" ];
then
  echo "No boot delay"
else
  #BOOT_DELAY=1
  echo "Sleeping $BOOT_DELAY seconds..."
fi

if [ "$BOOT_DEV" == "" ];
then
  echo "No boot dev"
else
  #BOOT_DEV=/dev/sda1
  echo "Booting from $BOOT_DEV..."
  $B_MNT -t vfat $BOOT_DEV /mnt
fi

if [ "$BOOT_ROOTFS" == "" ];
then
  echo "No rootfs"
else
  #BOOT_ROOTFS=rootfs.squashfs
  echo "Boot rootfs $BOOT_ROOTFS"
  $B_MNT -t squashfs /mnt/$BOOT_ROOTFS /newroot
fi
}

rootfs_exist() {
echo "Switch ROOT..."
$B_UMNT /proc
$B_UMNT /sys
exec switch_root /newroot /init
}

rootfs_not_exist() {
echo "Starting SH..."
exec /bin/sh
}

mountfs
[ -f /mnt/$BOOT_ROOTFS ] && rootfs_exist || rootfs_not_exist
